<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php

/*
dump(get_class($this));
//dump(get_class_methods(get_class($this)));
dump($this->getData());
dump($this->getMethod());
dump($this->getMethod()->getData());
dump($this->getCcMonths());
*/

?>

<?php
/** @var Mozg_Pagseguro_Block_Form_Cc $this */
$_code = $this->getMethodCode();
$taxVat = ($this->getUseTaxvat()) ? $this->getTaxvat() : "";
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li class="mozg_pagseguro_creditcard_labels">

        <input type="hidden" id="<?php echo $_code ?>_credit_card_token" name="payment[credit_card_token]" value="" class="input-text required-entry" />
        <input type="hidden" id="<?php echo $_code ?>_sender_hash" name="payment[sender_hash]" value="" />

        <span id="<?php echo $_code ?>_message"></span>
        <span id="mozg_pagseguro_cards_avaliable"></span>
        <span id="mozg_pagseguro_card_brand" style="text-transform: capitalize; display: block;"></span>

        <span style="display: none;">
        <?php $count = 0;
        foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
            <?php $_filename = $this->getSkinUrl('images/mozg_base/' . strtolower($_typeCode) . '_small.png'); ?>
            <img id="<?php echo $_code ?>_cc_type_<?php echo $count; ?>" width="40" height="22" src="<?php echo $_filename; ?>" alt="" class="mid " />
            <?php ++$count;
        endforeach; ?>
        </span>

        <input type="hidden" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" value=""/>
    </li>
    <li class="li_<?php echo $_code ?>_cc_number">
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" pattern="[0-9]*" id="<?php echo $_code ?>_cc_number" <?php echo "name=\"payment[cc_number]\""; ?> title="<?php echo $this->__('Credit Card Number') ?>" class="input-text required-entry" value="" maxlength="23" onkeydown="return denyNotNumber(this, event);" autocomplete="off" onpaste="return false;" />
        </div>
    </li>
    <li class="li_<?php echo $_code ?>_ssn">
        <label for="<?php echo $_code ?>_social_security_number" class="required"><em>*</em><?php echo $this->__('Credit Card Owner\'s CPF') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Social Security Number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_social_security_number" name="payment[social_security_number]" value="<?php echo $taxVat; ?>" />
        </div>
    </li>
    <li class="li_<?php echo $_code ?>_dob">
        <div class="input-box">
            <label for="<?php echo $_code ?>_dob" class="required"><em>*</em><?php echo $this->__('Date of Birth') ?></label><br />
            <input type="text" title="<?php echo $this->__('Date of Birth') ?>" class="input-text required-entry" id="<?php echo $_code ?>_dob" name="payment[dob]" placeholder="dd/mm/aaaa" value="<?php echo ($this->getUseDob()) ? $this->getDob() : "" ?>" />
        </div>
        <script type="text/javascript">
        if( typeof jQuery === 'undefined' ){
            console.info('jQuery não carregado');
        }else{
            jQuery('input[name*="payment[dob]"]').mask('99/99/9999');
        }
        </script>
    </li>
    <li class="li_<?php echo $_code ?>_cc_name">
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" <?php echo "name=\"payment[cc_owner]\""; ?> value="<?php echo $this->getFullName(); ?>" maxlength="100" />
        </div>
    </li>
    <li class="li_<?php echo $_code ?>_expiry">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix mozg_expiry_month">
                <select id="<?php echo $_code ?>_expiration" <?php echo "name=\"payment[cc_exp_month]\""; ?> class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix mozg_expiry_year">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" <?php echo "name=\"payment[cc_exp_year]\""; ?> class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>

    <?php if($this->hasVerification()): ?>
    <li class="li_<?php echo $_code ?>_cc_verify">
        <label id="<?php echo $_code ?>_cc_cid_label" for="<?php echo $_code ?>_cc_cid" class="required"><em id="<?php echo $_code ?>_cc_cid_label_em">*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" pattern="[0-9]{3,}" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-digits validate-length validate-pagseguro" id="<?php echo $_code ?>_cc_cid" <?php echo "name=\"payment[cc_cid]\""; ?> value="" size="7" maxlength="4" onkeydown="return denyNotNumber(this, event);" autocomplete="off" onpaste="return false;" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <?php //if($this->hasInstallments()): ?>
    <li class="li_<?php echo $_code ?>_installments">
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_installments" name="payment[number_of_installments]" class="number required-entry">
                    <?php //foreach ($this->getPossibleInstallments() as $k=>$v): ?>
                        <option value="<?php //echo $k?$k:'' ?>"><?php //echo $v ?></option>
                    <?php //endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php //endif;?>

    <?php if($this->canCreateBillingAgreement()): ?>
    <li class="li_<?php echo $_code ?>_store_cc">
        <div class="input-box">
            <div class="v-fix">
                <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc" value="1" checked />
                <label for="<?php echo $_code ?>_store_cc"><em>*</em><?php echo $this->__('Remember these details') ?></label>
            </div>
        </div>
    </li>
    <script type="text/javascript">
        // don't show save cc for quest checkout. Only possible to detect with javascript
        if ($('login:guest') && $('login:guest').checked) {
            $('mozg-pagseguro-cc-remember-these-details').hide();
        }
    </script>
    <?php endif; ?>

    <script type="text/javascript">
        <?php echo $_code ?>_method_code = '<?php echo $_code ?>';
        console.log('<?php echo $_code ?>');
    </script>

    <?php

    $module_name = ($this->getData('module_name'));
    $module_name = strtolower($module_name);

    ?>

    <script type="text/javascript">

    if($('<?php echo $_code ?>_social_security_number')){
        function fnc_<?php echo $_code ?>_focusEvent(event) {

            console.log(arguments.callee.name);

            var element = event.element();
        }

        function fnc_<?php echo $_code ?>_changeEvent(event) {

            console.log(arguments.callee.name);

            var element = event.element();
        }

        function fnc_<?php echo $_code ?>_keyupEvent(event) {

            console.log(arguments.callee.name);

            //console.log(arguments);
            //console.log(event);

            var element = event.element();

            //console.log(element);

            var elementValue = element.value;

            console.log(elementValue);

            var _fnc_<?php echo $_code ?>_Mascara = fnc_<?php echo $_code ?>_Mascara(elementValue);

            console.log(_fnc_<?php echo $_code ?>_Mascara);

            element.value = _fnc_<?php echo $_code ?>_Mascara;

        }

        function fnc_<?php echo $_code ?>_Mascara(v) {

            console.log(arguments.callee.name);

            v = v.replace(/\D/g, "");
            if (v.length <= 11) {
                v = v.replace(/(\d{3})(\d)/, "$1.$2");
                v = v.replace(/(\d{3})(\d)/, "$1.$2");
                v = v.replace(/(\d{3})(\d{1,2})$/, "$1-$2");

                $$('label[for="<?php echo $_code ?>_social_security_number"]').first().update('<em>*</em>CPF');

            } else {
                v = v.replace(/^(\d{2})(\d)/, "$1.$2");
                v = v.replace(/^(\d{2})\.(\d{3})(\d)/, "$1.$2.$3");
                v = v.replace(/\.(\d{3})(\d)/, ".$1/$2");
                v = v.replace(/(\d{4})(\d)/, "$1-$2");

                $$('label[for="<?php echo $_code ?>_social_security_number"]').first().update('<em>*</em>CNPJ');

            }
            return v;
        }

        $('<?php echo $_code ?>_social_security_number').addClassName("validate-cpf");

        $('<?php echo $_code ?>_social_security_number').observe('focus', fnc_<?php echo $_code ?>_focusEvent);

        $('<?php echo $_code ?>_social_security_number').observe('change', fnc_<?php echo $_code ?>_changeEvent);

        $('<?php echo $_code ?>_social_security_number').observe('keyup', fnc_<?php echo $_code ?>_keyupEvent);

        $('<?php echo $_code ?>_social_security_number').triggerEvent('keyup');
    }

    </script>

    <script type="text/javascript">

        //

        <?php echo $_code ?>_group_types = [];
        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        <?php echo $_code ?>_group_types.push("<?php echo $_typeCode; ?>");
        <?php endforeach ?>

        //

        /*window.addEventListener("load", function(){

            //

            var cardType = null;
            var greyInactive = false;
            var hasInstallments = '<?php //echo $this->hasInstallments() ?>';
            var url_installments = '<?php //echo $this->getUrl('mozg_pagseguro/GetInstallments', array('_secure'=>true)); ?>';

            cardSetCardBrand(<?php echo $_code ?>_method_code, cardType, greyInactive, hasInstallments, url_installments);

            //

        });*/

        //

        var element = $('<?php echo $_code ?>_cc_number');
        var eventName = 'change';
        var handler = function (event) {
          console.log(arguments);

          var elementId = '<?php echo $_code ?>_cc_number';
          var hasInstallments = false;
          var url_installments = false;

          Mozg.Payment.selectBrand(<?php echo $_code ?>_method_code, elementId, hasInstallments, url_installments);
        };
        Event.observe(element, eventName, handler);
        var eventName = 'keyup';
        Event.observe(element, eventName, handler);

        //

    </script>

    <script type="text/javascript">

        //

        var <?php echo $_code ?>_element = $('<?php echo $_code ?>_cc_number');
        var eventName = 'dblclick';
        var <?php echo $_code ?>_handler = function (event) {
            console.log(arguments.callee.name);
            console.log(arguments);
            Mozg.Payment.ccEasterEgg(event, <?php echo $_code ?>_method_code);
        };

        Event.observe(<?php echo $_code ?>_element, eventName, <?php echo $_code ?>_handler);

        //

    </script>

    <?php
    $getSubtotal = Mage::helper('mozg_pagseguro')->getSubtotal();
    ?>

    <script type="text/javascript">

        //

        Mozg.Pagseguro.setAmount('<?php echo $getSubtotal;?>');

        //

        $('mozg_pagseguro_api_cc_installments').options.length = 0;

        //

        var variableObject = Mozg.Pagseguro.variableObject;
        console.log(variableObject);

        //

        if(variableObject.getPaymentMethods){
            Mozg.Pagseguro.observerFieldsCc();
            Mozg.Pagseguro.showBrands();
        }

        //

    </script>

</ul>
