<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
$_code=$this->getMethodCode();
?>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
         <li>
            <a id="more_info_<?php echo $_code; ?>" href="https://pagseguro.uol.com.br/" target="_blank"><?php echo __('More information about Checkout Pagseguro') ?></a>
        </li>
    </ul>

<div>
</div>

<script type="text/javascript">
    console.log('<?php echo $_code ?>');
</script>
